//Assignment No. 11 "Deque Operations"
#include<iostream>
#include<deque>
#include<string>
#include<stdlib.h>
using namespace std;
int main()
{
	deque<int> dq;
	deque<int>::iterator it;
	int choice,item;
	while(1)
	{
		cout<<"\nDEQUE IMPLEMENTATION IN STL";
		cout<<"\n1.INSERT ELEMENT AT END"; 
		cout<<"\n2.INSERT ELEMENT AT FRONT";
		cout<<"\n3.DELETE ELEMENT AT END";
		cout<<"\n4.DELETE ELEMENT AT FRONT";
		cout<<"\n5.FRONT ELEMENT OF DEQUE";	
		cout<<"\n6.LAST ELEMENT OF DEQUE";
		cout<<"\n7.SIZE OF DEQUE";
		cout<<"\n8.DISPLAY DEQUE";
		cout<<"\n9.EXIT";
		cout<<"\nENTER YOUR CHOICE : ";
		cin>>choice;

		switch(choice)
		{
			case 1:
				cout<<"\nEnter value to be inserted at the end : ";
				cin>>item;
				dq.push_back(item);
				break;
			case 2:
				cout<<"\nEnter value to be inserted at the front : ";
				cin>>item;
				dq.push_front(item);
				break;
			case 3:
				item=dq.back();
				dq.pop_back();
				cout<<"\nElement "<<item<<" deleted";
				break;
			case 4:
				item=dq.front();
				dq.pop_front();
				cout<<"\nElement "<<item<<" deleted";
				break;
			case 5:
				cout<<"\nFront element of the deque : ";
				cout<<dq.front();
				break;
			case 6:
				cout<<"\nBack element of the deque : ";
				cout<<dq.back();
				break;
			case 7:
				cout<<"\nSize of the deque "<<dq.size();
				break;
			case 8:
				cout<<"\nElements of deque : ";
				for(it=dq.begin();it!=dq.end();it++)
					cout<<*it<<" ";
				break;
			case 9:exit(0);
			default:cout<<"\nWrong choice\n";							
		}
	}
	return 0;
}
/*
DEQUE IMPLEMENTATION IN STL
1.INSERT ELEMENT AT END
2.INSERT ELEMENT AT FRONT
3.DELETE ELEMENT AT END
4.DELETE ELEMENT AT FRONT
5.FRONT ELEMENT OF DEQUE
6.LAST ELEMENT OF DEQUE
7.SIZE OF DEQUE
8.DISPLAY DEQUE
9.EXIT
ENTER YOUR CHOICE : 1

Enter value to be inserted at the end : 3

DEQUE IMPLEMENTATION IN STL
1.INSERT ELEMENT AT END
2.INSERT ELEMENT AT FRONT
3.DELETE ELEMENT AT END
4.DELETE ELEMENT AT FRONT
5.FRONT ELEMENT OF DEQUE
6.LAST ELEMENT OF DEQUE
7.SIZE OF DEQUE
8.DISPLAY DEQUE
9.EXIT
ENTER YOUR CHOICE : 1

Enter value to be inserted at the end : 2

DEQUE IMPLEMENTATION IN STL
1.INSERT ELEMENT AT END
2.INSERT ELEMENT AT FRONT
3.DELETE ELEMENT AT END
4.DELETE ELEMENT AT FRONT
5.FRONT ELEMENT OF DEQUE
6.LAST ELEMENT OF DEQUE
7.SIZE OF DEQUE
8.DISPLAY DEQUE
9.EXIT
ENTER YOUR CHOICE : 2

Enter value to be inserted at the front : 5

DEQUE IMPLEMENTATION IN STL
1.INSERT ELEMENT AT END
2.INSERT ELEMENT AT FRONT
3.DELETE ELEMENT AT END
4.DELETE ELEMENT AT FRONT
5.FRONT ELEMENT OF DEQUE
6.LAST ELEMENT OF DEQUE
7.SIZE OF DEQUE
8.DISPLAY DEQUE
9.EXIT
ENTER YOUR CHOICE : 8

Elements of deque : 5 3 2	
DEQUE IMPLEMENTATION IN STL
1.INSERT ELEMENT AT END
2.INSERT ELEMENT AT FRONT
3.DELETE ELEMENT AT END
4.DELETE ELEMENT AT FRONT
5.FRONT ELEMENT OF DEQUE
6.LAST ELEMENT OF DEQUE
7.SIZE OF DEQUE
8.DISPLAY DEQUE
9.EXIT
ENTER YOUR CHOICE : 3

Element 2 deleted
DEQUE IMPLEMENTATION IN STL
1.INSERT ELEMENT AT END
2.INSERT ELEMENT AT FRONT
3.DELETE ELEMENT AT END
4.DELETE ELEMENT AT FRONT
5.FRONT ELEMENT OF DEQUE
6.LAST ELEMENT OF DEQUE
7.SIZE OF DEQUE
8.DISPLAY DEQUE
9.EXIT
ENTER YOUR CHOICE : 8

Elements of deque : 5 3	
DEQUE IMPLEMENTATION IN STL
1.INSERT ELEMENT AT END
2.INSERT ELEMENT AT FRONT
3.DELETE ELEMENT AT END
4.DELETE ELEMENT AT FRONT
5.FRONT ELEMENT OF DEQUE
6.LAST ELEMENT OF DEQUE
7.SIZE OF DEQUE
8.DISPLAY DEQUE
9.EXIT
ENTER YOUR CHOICE : 2

Enter value to be inserted at the front : 6

DEQUE IMPLEMENTATION IN STL
1.INSERT ELEMENT AT END
2.INSERT ELEMENT AT FRONT
3.DELETE ELEMENT AT END
4.DELETE ELEMENT AT FRONT
5.FRONT ELEMENT OF DEQUE
6.LAST ELEMENT OF DEQUE
7.SIZE OF DEQUE
8.DISPLAY DEQUE
9.EXIT
ENTER YOUR CHOICE : 4

Element 6 deleted
DEQUE IMPLEMENTATION IN STL
1.INSERT ELEMENT AT END
2.INSERT ELEMENT AT FRONT
3.DELETE ELEMENT AT END
4.DELETE ELEMENT AT FRONT
5.FRONT ELEMENT OF DEQUE
6.LAST ELEMENT OF DEQUE
7.SIZE OF DEQUE
8.DISPLAY DEQUE
9.EXIT
ENTER YOUR CHOICE : 8

Elements of deque : 5 3	
DEQUE IMPLEMENTATION IN STL
1.INSERT ELEMENT AT END
2.INSERT ELEMENT AT FRONT
3.DELETE ELEMENT AT END
4.DELETE ELEMENT AT FRONT
5.FRONT ELEMENT OF DEQUE
6.LAST ELEMENT OF DEQUE
7.SIZE OF DEQUE
8.DISPLAY DEQUE
9.EXIT
ENTER YOUR CHOICE : 5

Front element of the deque: 5
DEQUE IMPLEMENTATION IN STL
1.INSERT ELEMENT AT END
2.INSERT ELEMENT AT FRONT
3.DELETE ELEMENT AT END
4.DELETE ELEMENT AT FRONT
5.FRONT ELEMENT OF DEQUE
6.LAST ELEMENT OF DEQUE
7.SIZE OF DEQUE
8.DISPLAY DEQUE
9.EXIT
ENTER YOUR CHOICE : 6

Back element of the deque : 3
DEQUE IMPLEMENTATION IN STL
1.INSERT ELEMENT AT END
2.INSERT ELEMENT AT FRONT
3.DELETE ELEMENT AT END
4.DELETE ELEMENT AT FRONT
5.FRONT ELEMENT OF DEQUE
6.LAST ELEMENT OF DEQUE
7.SIZE OF DEQUE
8.DISPLAY DEQUE
9.EXIT
ENTER YOUR CHOICE : 7

Size of the deque 2
DEQUE IMPLEMENTATION IN STL
1.INSERT ELEMENT AT END
2.INSERT ELEMENT AT FRONT
3.DELETE ELEMENT AT END
4.DELETE ELEMENT AT FRONT
5.FRONT ELEMENT OF DEQUE
6.LAST ELEMENT OF DEQUE
7.SIZE OF DEQUE
8.DISPLAY DEQUE
9.EXIT
ENTER YOUR CHOICE : 9

*/
